### ISSUE TITLE
Manage Solution Settings | Context Set page goes wild and blinks like a christmas tree (project can not be built)

### ISSUE THREAD

**Issue by AkiMakkonen-AlifSemi** [ARM-software/vscode-cmsis-csolution#120]
Version v1.44.0

To reproduce:
Clone Alif's template project

`git clone https://github.com/alifsemi/alif_vscode-template.git
cd alif_vscode-template/
git submodule update --init`

Open folder with VS Code

Click the "Manage Solution"  ( the sprocket icon )

Try to change some of the settings like Active Project

-->footer bar starts blinking
-->project selection checkbox(es) start blinking
-->csolution hits the 'knight rider' mode

Used to work with v1.40.0 (even though that version also is fragile and unstable when selecting the check boxes. One needs to wait a while before touching a next checkbox in order to avoid trouble.)

**Comment by jkrech** [comment]
Thanks for reporting the problem. I am able to reproduce it.

The problem seems to be caused by the file extension `*.yaml` instead of `*.yml`.
The CMSIS Solution fails to write an `alif.cbuild-set.yml` file with valid contexts if the project files use the extension `*.cproject.yaml`. The "Manage Solution" dialog fails to read it and triggers another attempt to write the cbuild-set.yml.
Each time the `cbuild-set.yml` changes the `cbuild setup` is invoked, however failing due to an invalid cbuild-set.yml, hence the X-mas tree.

The workaround is to rename all `*.cproject.*` files from `*.yaml` to `*.yml` and update the `project:` nodes in the csolution file accordingly.
We will provide a fix ASAP.
