### ISSUE TITLE
uv2csolution optimize not considered

### ISSUE THREAD

**Issue by minicarpet** [ARM-software/vscode-cmsis-csolution#131]
Type: Bug Report

**Describe the bug**
- OS and Version: Windows x64
- VS Code Version: 1.95.3
- Keil uVision Version: 5.41.0
- Extension Version: 1.44.0
- Target Device: STMicroelectronics::STM32H523CEUx
- Other extensions you installed (and if the issue persists after disabling them):

Converting a .uvprojx does not consider the optimization

**To Reproduce**
1. Create a keil project with optimization

![image](https://github.com/user-attachments/assets/837255cc-854d-417d-b4a3-29d8bf562a2c)

3. Click on "Convert a uVision Project" and choose the project just created

![image](https://github.com/user-attachments/assets/0c3d0bfc-68ea-4c90-93de-2b1009102475)

4. See error (optimize yml should not be "debug")

![image](https://github.com/user-attachments/assets/e56a0ee0-837b-4401-81eb-30622c1f9673)

> **_NOTE:_**  Optimize field [(yml description)](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#optimize) seems to not support all possible options.

**Expected behavior**
Optimize should be:
> debug if O0 or O1 selected
> speed if Ofast selected
> size if Oz image size selected
> balanced if Os balanced
No possible value for others values into keil ??

**Comment by mguzmanm** [comment]
If "Debug Information" is set in "Output" tab ("Options for target" window in uVision), "Optimization" value in "C/C++ (AC6)" tab, will be overwritten with "debug" value. Please see requirement in https://jira.arm.com/browse/SDMDK-10727. Hence, this issue is not a bug.

**Comment by jkrech** [comment]
The [optimize: yml node](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#optimize) deliberately chooses "generic" levels rather than toolchain specific command line flags. When mapping from uVision settings to the CMSIS Solution format multiple uVision values need to be mapped to a single YML value.

The unexpected behavior is triggered by the setting Options for Target -> Output Tab -> Debug Information.
This currently forces the optimization to "debug" to ensure best possible debug experience. Please uncheck that option in uVision to enable optimization.

**uVision:  => CMSIS Solution**
<default> =>  
-O0  => optimize: none
-O1 => optimize: none
-O2 => optimize: speed
-O3 => optimize: speed
-Ofast => optimize: speed
-Os balanced => optimize: balanced
-Oz image size => optimize: size
-Omax => optimize: speed

**Comment by minicarpet** [comment]
-Omax seems to put balanced insead of speed, but it's fine for ma as I use -Ofast, thank you

**Comment by chentang16** [comment]
> The [optimize: yml node](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#optimize) deliberately chooses "generic" levels rather than toolchain specific command line flags. When mapping from uVision settings to the CMSIS Solution format multiple uVision values need to be mapped to a single YML value.
> 
> The unexpected behavior is triggered by the setting Options for Target -> Output Tab -> Debug Information. This currently forces the optimization to "debug" to ensure best possible debug experience. Please uncheck that option in uVision to enable optimization.
> 
> **uVision: => CMSIS Solution** `<default>` => -O0 => optimize: none -O1 => optimize: none -O2 => optimize: speed -O3 => optimize: speed -Ofast => optimize: speed -Os balanced => optimize: balanced -Oz image size => optimize: size -Omax => optimize: balanced
> 
> Please note that there is always the possibility to specify toolchain specific command line options using the [misc:](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#misc) node in case the generic abstractions lack granularity.

In my opinion such a mapping between the "generic" levels and -O levels should be well documented somewhere. Users would instinctually assume the compiler options are one-to-one converted to the csolution project.
