### ISSUE TITLE
PROMBLEMS view cannot show 'missing pack' message

### ISSUE THREAD

**Issue by UniverGao** [ARM-software/vscode-cmsis-csolution#24]
Type: Bug Report

**Describe the bug**
- OS and Version: Ubuntu 18.04 WSL2 in windows 11 Professional 22H2
- VS Code Version: 1.76.2(user setup) by using 'Remote Development' extention 
- Extension Version:0.17.0
- Target Device:Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
- The 'PROBLEMS' tag didn't show missing pack after executing 'Convert' command by using 'Hello.csolution.yml' but 'OUTPUT' tag showed 'missing pack' message.

**To Reproduce**
1. Clone example in 'https://github.com/Open-CMSIS-Pack/csolution-examples.git'
2. cd ./csolution-examples/Hello and execute *code .* command
3. Project convert automatically and *OUTPUT* tag shows missing pack problems
4. Open Hello.csolution.yml but *PROBLEM* tag doesn't show missing pack message

**Expected behavior**
- If one or several packs are missing, errors display in the PROBLEMS view (mentioned in README.md of 'vscode-cmsis-csolution' repository).

**Code sample and logs**
//

**Screenshots**
![image](https://user-images.githubusercontent.com/54207463/228219919-e1e83102-b02b-4dfa-936d-e28d5858f652.png)

**Additional context**
//

**Comment by mcgordonite** [comment]
Hi @UniverGao, it's not immediately obvious what the cause is here, I wasn't able to reproduce it with the csolution-examples repository. Some things to check:

1. Has the context view loaded correctly, showing the active project, target & build type? If it hasn't, the extension might not have activated correctly. It should show something like this:
    ![Contexts](https://user-images.githubusercontent.com/12599255/228274273-fe781ab4-0a1a-42f2-9c9c-8aedb770dfaf.png)
2. Is the CMSIS pack root configured correctly in WSL? It's possible the csolution convert command is using a different pack cache from the VS Code extension. Do you have a `CMSIS_PACK_ROOT` environment variable set in WSL? Is the `cmsis-csolution.packCachePath` VS Code setting configured for your WSL environment? I've not tried this in WSL, but I think the default would be having `CMSIS_PACK_ROOT` set to something like `/home/ug/.cache/arm/packs`, and leave the VS Code setting blank.

**Comment by UniverGao** [comment]
@mcgordonite 
1. It shows like this but no *ACTION* tag
![image](https://user-images.githubusercontent.com/54207463/228497589-6cd8e100-d285-4c62-8a4f-00d6c0cc018d.png)
2. I redefined the environment variable followed the instruction, 
the variable *CMSIS_PACK_ROOT * is '/home/ug/downloads/cmsis-pack' 
*cmsis-csolution.packCachePath* is set as default and I didn't change it
![image](https://user-images.githubusercontent.com/54207463/228497983-b155aee9-b142-4799-9d4b-4e96439fe4e5.png)

best regards

**Comment by mcgordonite** [comment]
Hi, one more thing to check: are the packs defined in the cproject or csolution file? Support for packs in cproject files was only added to the spec recently and hasn't been implemented in this extension yet.

**Comment by UniverGao** [comment]
> Hi, one more thing to check: are the packs defined in the cproject or csolution file? Support for packs in cproject files was only added to the spec recently and hasn't been implemented in this extension yet.

![image](https://user-images.githubusercontent.com/54207463/230610977-8b37175a-5edf-46e1-95d5-206d85dadcc9.png)

You can see that all packs can be installed by using 'cpackget' command
