### ISSUE TITLE
Click on "Create new solution" to prompts network error。

### ISSUE THREAD

**Issue by haiqinJack** [ARM-software/vscode-cmsis-csolution#67]
**Describe the bug**
- OS and Version: MacOS 12.6
- VS Code Version: 1.89.1
- Extension Version: v1.18.2
- Click on "Create new solution" to  prompts network error。
﻿
![1233](https://github.com/ARM-software/vscode-cmsis-csolution/assets/35925781/41a8b5b0-ab1e-442b-a6f4-569eea20e7a3)

**Comment by mcgordonite** [comment]
Hi @haiqinJack, it looks like a process the extension uses to read CMSIS packs has failed to start. It would help to see the logs. To get the logs:
1. Open VS Code.
2. Run "Developer: Toggle Developer Tools" from the command palette (CMD-SHIFT-P).
3. Open the Console view in the developer tools.
4. Open the Create Solution UI.
5. Right click the text in the Console view and select "Save As".

**Comment by haiqinJack** [comment]
@mcgordonite thank.

![222](https://github.com/ARM-software/vscode-cmsis-csolution/assets/35925781/1206c12f-e081-4b7c-8e94-f1bc67d8b2c0)

**Comment by mcgordonite** [comment]
Hi, sorry for the slow response. Thanks for sending over the logs. The `14 UNAVAILABLE` messages in the logs confirm the issue was related to the child process the extension uses to read CMSIS packs, but there aren't any clues as to the cause.

More things to try:
* You are on quite an old version of the Csolution extension. The latest is 1.35.0 (see here: https://marketplace.visualstudio.com/items?itemName=Arm.cmsis-csolution). Does updating help? You may be on an older version of VS Code too.
* Are you working behind a corporate proxy or equivalent?

**Comment by haiqinJack** [comment]
@mcgordonite thank.i have created a new system user and can now use it.
